In [ ]:
import numpy as np

#**ndarray 개요**

### np.array(객체)

객체가 ndarray타입 배열로 변환됨

### ndarray타입 배열명.shape

- 1차원 배열
(데이터 수, )
- 2차원 배열
(row 수, col 수)
- 3차원 배열
(2차원 배열의 개수, row수, col 수)

### ndarray.ndim

객체의 차원

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3]
                  ,[4,5,6]])
print('array3 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array3 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)

In [ ]:
print('arrray1:{0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

arrray1:1차원,array2:2차원,array3:2차원

In [ ]:
# 3차원 배열 생성
arr = np.array([[[1, 2,4], [3, 4,6]],[[5,1, 6], [7,1,28]], [[5, 1,6], [7, 1,8]]])

# 배열의 shape 출력
print(arr.shape)

(3, 2, 3)

#**ndarray의 데이터타입**

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64

In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.3])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32

#**ndarray를 편리하게 생성하기-arange,zeros,ones**
### arange(끝값) / arrange(시작값,끝값)

range함수처럼 시작값도 부여가능

### zeros(row수,col수) / zeros(row수,col수,dtype=’’)

0으로 채운 ndarray 생성

dtype 안정하면 default값 - float64형

### ones(row수,col수)

1로 채운 ndarray 생성

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)

In [ ]:
zero_array = np.zeros((2,3),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0 0]
 [0 0 0]]
int32 (2, 3)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)

#**ndarray의 차원과 크기를 변경하는 reshape()**

In [ ]:
array1 = np.arange(10)
print('array1 : \n',array1)

array2 = array1.reshape(2,5)
print('array2: \n',array2)

array3 = array1.reshape(5,2)
print('array3: \n',array3)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

In [ ]:
#array1.reshape(4,3) # Value Error

In [ ]:
array1 = np.arange(10)
print('array1 : \n',array1)

array2 = array1.reshape(-1,5)
print('array2: \n',array2.shape)

array3 = array1.reshape(5,-1)
print('array3: \n',array3.shape)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2:
 (2, 5)
array3:
 (5, 2)

In [ ]:
array1 = np.arange(8) #array1은 배열의 원소가 8개인 1차원 리스트
array3d=array1.reshape((2,2,2)) #array3d는 2x2짜리가 2개인 3차원 리스트
print('array3d: \n',array3d.tolist())

array5=array3d.reshape(-1,1) #array5는 array3d를 2차원으로 변환
print('array5: \n',array5.tolist())
print('array5 shape:',array5.shape)

array6 = array1.reshape(-1,1) #array6은 array1(1차원)을 2차원으로 변환
print('array5: \n',array5.tolist())
print('array5 shape:',array5.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)

#**넘파이 ndarray의 데이터 세트 선택하기 - indexing**

##단일값 추출

In [ ]:
array1 = np.arange(start=1,stop=10)
print('array1:',array1)

value = array1[2]
print('value:',value)
print(type(value))

print('맨뒤의 값:',array1[-1],'맨 뒤에서 두번째 값:',array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨뒤의 값: 9 맨 뒤에서 두번째 값: 8

In [ ]:
array1[0]= 9 #array1[0]의 type은 ndarray가아니라 int형
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]

In [ ]:
array1d= np.arange(start=1,stop=10)
array2d= array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0]) #row,col 이라 지칭X , axis0,axis1
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9

##슬라이싱

In [ ]:
array1 = np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>

In [ ]:
array1 = np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d= array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)

##팬시 인덱싱(Fancy Indexing)

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]

In [ ]:
array1d = np.arange(start=1,stop=10)
# 데이터값>5인 데이터만 추출
array3= array1d[array1d>5]
print("array1d > 5 인 불린 인덱싱 결과값:",array3)

array1d > 5 인 불린 인덱싱 결과값: [6 7 8 9]

In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = [False,False,False,False,False, True,True,True,True]
array3 = array1d[boolean_indexes]
print('불린인덱스로 필터링 결과 : ',array3)

불린인덱스로 필터링 결과 :  [6 7 8 9]

## 행렬의 정렬- sort()와 argsort()

In [ ]:
org_array = np.array([3,1,9,5])
print('원본행렬:',org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬:",sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]

In [ ]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d,axis=0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print('col 방향으로 정렬:\n', sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
col 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 정렬 시 원본 행렬의 인덱스 내림차순:',sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 정렬 시 원본 행렬의 인덱스 내림차순: [2 3 0 1]

In [ ]:
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']

##선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [ ]:
#행렬 내적
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]

In [ ]:
#전치 행렬
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]

#**데이터 핸들링 - 판다스**

#판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [ ]:
import pandas as pd

In [ ]:
titanic_df = pd.read_csv('/content/Titanic/train.csv')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [ ]:
titanic_df=pd.read_csv('/content/Titanic/train.csv')
print('titanic 변수 type:',type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
print('DataFrame 크기:',titanic_df.shape)

DataFrame 크기: (891, 12)

In [ ]:
titanic_df.info() #data 건수, data type, null 건수 알 수 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_df.describe() #column형 data값 4Q 분포도,평균값,최솟값,최댓값 나타냄
#int형,float형만 출력 / object형 제외

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
valueCount = titanic_df['Pclass'].value_counts()
print(valueCount)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
titanic_pclass= titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [ ]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [ ]:
valueCount= titanic_df['Pclass'].value_counts()
print(type(valueCount))
print(valueCount)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
print('titanic_df 데이터 건수:',titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

#DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

##리스트, 딕셔너리, ndarray > DataFrame

In [ ]:
col_name1=['col1'] #1차원 > col명 1개
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:',array1.shape)
# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1,columns=col_name1) #columns 명을 col1로 저장
print('1차원 리스트로 만든 DataFrame:\n',df_list1)
# numpy ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n',df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [ ]:
#2x3 ndarray > 3개의 col명 필요
col_name2 = ['col1','col2','col3']

list2=[[1,2,3],
       [11,12,13]]
array2 = np.array(list2)
print('array2 shape:',array2.shape)
df_list2 = pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n',df_list2)

df_array2 = pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n',df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [ ]:
#key는 문자열 column명으로 매핑, Value는 리스트(ndarray)형 column데이터로 매핑
dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

##DataFrame > 리스트, 딕셔너리, ndarray

In [ ]:
# DataFrame > ndarray
array3 = df_dict.values
print('df_dict.values 타입:',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [ ]:
# DataFrame > 리스트
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:',type(list3))
print(list3)

# DataFrame > 딕셔너리
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict 타입:',type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

#DataFrame의 column 데이터 세트 생성과 수정

In [ ]:
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [ ]:
titanic_df['Age_by_10']= titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [ ]:
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

#DataFrame 데이터삭제


#drop() 원형
     DataFrame.drop(labels = None, axis = 0, index = None,
               columns = None, level = None,
               inplace = False, errors='raise')

In [ ]:
titanic_drop_df = titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [ ]:
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [ ]:
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'],
                              axis=1,inplace=True)
print('inplace = True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

inplace = True로 drop 후 반환된 값: None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [ ]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('***before axis 0 drop***')
print(titanic_df.head(3))

titanic_df.drop([3,4,5],axis=0,inplace = True)

print('***after axis 0 drop***')
print(titanic_df.head(3))

***before axis 0 drop***
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
***after axis 0 drop***
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

#Index 객체

In [ ]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('/content/Titanic/train.csv')
# Index 객체 추출
indexes = titanic_df.index
print(indexes)
# Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [ ]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [ ]:
#indexes[0] = 5 # Type error

In [ ]:
series_fair = titanic_df['Fare']
print('Fair Series max값:',series_fair.max())
print('Fair Series sum값:',series_fair.sum())
print('sum() Fair Series:',sum(series_fair))
print('Fair Series + 3: \n',(series_fair + 3).head(3))

Fair Series max값: 512.3292
Fair Series sum값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [ ]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [ ]:
print('### before reset_index ###')
valueCounts = titanic_df['Pclass'].value_counts()
print(valueCounts)
print('value_counts 객체 변수 타입:',type(valueCounts))
new_valueCounts = valueCounts.reset_index(inplace=False)
print('### after reset_index ###')
print(new_valueCounts)
print('new_value_counts 객체 변수 타입:',type(new_valueCounts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### after reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

#데이터 셀렉션 및 필터링

##DataFrame [ ] 연산자

In [ ]:
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived','Pclass']].head(3))
#print('[]안에 숫자 index는 keyError 오류 발생:\n',titanic_df[0]) #KeyError

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

In [ ]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [ ]:
titanic_df[titanic_df['Pclass']==3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

##DataFrame iloc[ ] 연산자

In [ ]:
data = {'Name':['Nayeon','Jeongyeon','Jihyo','Momo'],
        'Year':[1995,1996,1997,1996],
        'Gender':['Female','Female','Female','Female']}
data_df = pd.DataFrame(data,index=['one','two','three','four'])
data_df

            Name  Year  Gender
one       Nayeon  1995  Female
two    Jeongyeon  1996  Female
three      Jihyo  1997  Female
four        Momo  1996  Female

In [ ]:
data_df.iloc[0,0]

'Nayeon'

In [ ]:
#data_df.iloc[0,'Name'] #[]안에 col이름,인덱스값 입력하면 오류 , ValueError

In [ ]:
#data_df.iloc['one',0] # []안에 인덱스값 입력 - ValueError

In [ ]:
print("\n 맨 마지막 칼럼 데이터[:,-1]\n",data_df.iloc[:,-1])
print("\n 맨 마지막 칼럼 빼고 모든 데이터[:,-1]\n",data_df.iloc[:,:-1])

 맨 마지막 칼럼 데이터[:,-1]
 one      Female
two      Female
three    Female
four     Female
Name: Gender, dtype: object

 맨 마지막 칼럼 빼고 모든 데이터[:,-1]
             Name  Year
one       Nayeon  1995
two    Jeongyeon  1996
three      Jihyo  1997
four        Momo  1996

##DataFrame loc[ ] 연산자

In [ ]:
data_df.loc['one','Name'] #loc[인덱스값,col명]

'Nayeon'

In [ ]:
#data_df.loc[0,'Name'] #KeyError, loc[]안에 0이 들어감

In [ ]:
print('위치기반 iloc slicing\n',data_df.iloc[0:1,0],'\n')
print('명칭기반 iloc slicing\n',data_df.loc['one':'two','Name'])
# loc은 [시작:끝] 에서 끝도 포함됨

위치기반 iloc slicing
 one    Nayeon
Name: Name, dtype: object

명칭기반 iloc slicing
 one       Nayeon
two    Jeongyeon
Name: Name, dtype: object

## 불린 인덱싱

In [ ]:
titanic_df = pd.read_csv('/content/Titanic/train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [ ]:
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [ ]:
titanic_df.loc[titanic_df['Age'] > 60,['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [ ]:
titanic_df[(titanic_df['Age'] > 60)&(titanic_df['Pclass']==1)
            & (titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [ ]:
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1 & cond2 & cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

#정렬, Aggregation 함수, GroupBy 적용

##DataFrame,Series의 정렬 - sort_values()

### by, ascending, inplace

In [ ]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [ ]:
titanic_sorted= titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

##Aggregation 함수 적용
###min(), max(), sum(), count(), mean()

In [ ]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

##groupby() 적용

In [ ]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [ ]:
titanic_df.groupby('Pclass')['Age'].agg(['max','min']) #FutureWarning - max,min > 'max','min'

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
agg_format = {'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

#결손 데이터 처리하기

##isna()로 결손 데이터 여부 확인

In [ ]:
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [ ]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

##fillna()로 결손 데이터 대체하기

In [ ]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [ ]:
titanic_df['Age']= titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

#apply lambda 식으로 데이터 가공

In [ ]:
def get_square(a):
  return a**2

print('3의 제곱은:',get_square(3))

3의 제곱은: 9

In [ ]:
lambda_square = lambda x: x**2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9

In [ ]:
a = [1,2,3]
squares = map(lambda x: x**2,a)
list(squares)

[1, 4, 9]

In [ ]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [ ]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x: 'Child' if x<=15
                                                    else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [ ]:
titanic_df['Age_cat']= titanic_df['Age'].apply(lambda x: 'Child' if x<=15
                                                    else ('Adult' if x<=60
                                                           else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [ ]:
def get_category(age):
  cate = ''
  if age <= 5: cate = 'Baby'
  elif age<= 12: cate= 'Child'
  elif age<= 18: cate= 'Teenager'
  elif age<= 25: cate= 'Student'
  elif age<= 35: cate= 'Young Adult'
  elif age<= 60: cate= 'Adult'
  else: cate = 'Elderly'

  return cate

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult